# Generated by Django 5.2.6 on 2025-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_header', models.CharField(default='CustomyShop Admin', max_length=200)),
                ('site_title', models.CharField(default='CustomyShop Portal', max_length=200)),
                ('index_title', models.CharField(default='Dashboard', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('footer_text', models.TextField(default='All rights reserved © CustomyShop Online Store')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('email_subscription_text', models.CharField(default='Subscribe for latest news:', max_length=255)),
                ('contact_number', models.CharField(default='+98 917 411 6470', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
