# Generated by Django 5.2.6 on 2025-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
