# Generated by Django 5.2.6 on 2025-09-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0003_rename_store_storeitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_store', to='stores.store'),
        ),
    ]
