# Generated by Django 5.2.6 on 2025-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_store_customuser_phone_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
