# Generated by Django 5.2.6 on 2025-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
