# Generated by Django 5.2.6 on 2025-09-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_sellerrequest_status_alter_store_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='Store',
            new_name='store',
        ),
    ]
