# Generated by Django 5.2.6 on 2025-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed')], default=0),
        ),
    ]
