# Generated by Django 5.2.6 on 2025-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
